### ISSUE TITLE
Excited about the new N:M topk functionality!

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb_vss#34]
Just read your [blog post on duckdb.org](https://duckdb.org/2024/10/23/whats-new-in-the-vss-extension.html). This sounds perfect for tasks such as record linkage, particularly the blocking stage, where you must generate candidate pairs of records before further analysis and classifying them as match/non-match. I am excited to experiment with adding this to a hobby project of mine, [mismo](www.github.com/NickCrews/mismo), and may come back with questions if I run into any issues. Thanks for your work! Feel free to close this once you see it.

**Comment by Maxxen** [comment]
Thanks :) feel free to post questions/issues as they arrive
